//> using publish.organization "io.github.MaciejG604"
//> using publish.name "weird_foo"
//> using publish.version "1.0.0"
//> using publish.repository "central-s01"
//> using publish.license "Apache-2.0"
//> using publish.url "https://github.com/MaciejG604/foo"
//> using publish.versionControl "github:MaciejG604/foo"
//> using publish.developer "Maciej G||https://github.com/MaciejG604"